#include "parameters.h"

uint32_t seq_gen_buffer[BUFF_SIZE];

ELECTROCHEMICAL_DPV_PARAMETERS dpv_lp_loop = (ELECTROCHEMICAL_DPV_PARAMETERS) {
	.e_begin = -0.6 * ELECTROCHEMICAL_UNIT,
	.e_end = 0.6 * ELECTROCHEMICAL_UNIT,
	.e_step = 0.01 * ELECTROCHEMICAL_UNIT,
	.e_pulse = 0.05 * ELECTROCHEMICAL_UNIT,
	.t_pulse = 0.05 * ELECTROCHEMICAL_UNIT,
	.scan_rate = 0.05 * ELECTROCHEMICAL_UNIT,
	.inversion_option = ELECTROCHEMICAL_DPV_INVERSION_OPTION_INVERT_NONE,
};

ELECTROCHEMICAL_DPV_PARAMETERS dpv_hs_loop = (ELECTROCHEMICAL_DPV_PARAMETERS) {
	.e_begin = -0.4 * ELECTROCHEMICAL_UNIT,
	.e_end = 0.3 * ELECTROCHEMICAL_UNIT,
	.e_step = 0.02 * ELECTROCHEMICAL_UNIT,
	.e_pulse = 0.05 * ELECTROCHEMICAL_UNIT,
	.t_pulse = 0.05 * ELECTROCHEMICAL_UNIT,
	.scan_rate = 0.05 * ELECTROCHEMICAL_UNIT,
	.inversion_option = ELECTROCHEMICAL_DPV_INVERSION_OPTION_INVERT_BOTH,
};
