#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ad5940_electrochemical_utils.h"

extern AD5940_ELECTROCHEMICAL_AFERefCfg_Type utl_ad5940_electrochemical_utility_AFERefCfg_Type;

extern AD5940_ELECTROCHEMICAL_LPDACfg_Type utl_ad5940_electrochemical_utility_LPPACfg_Type;

extern AD5940_ELECTROCHEMICAL_LPTIACfg_Type utl_ad5940_electrochemical_utility_LPTIACfg_Type;

extern AD5940_ELECTROCHEMICAL_HSTIACfg_Type utl_ad5940_electrochemical_utility_HSTIACfg_Type;

extern AD5940_ELECTROCHEMICAL_DSPCfg_Type utl_ad5940_electrochemical_utility_DSPCfg_Type;

#ifdef __cplusplus
}
#endif
