#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include "ad5940_electrochemical_utils.h"


extern AD5940_ELECTROCHEMICAL_AFERefCfg_Type utl_ad5940_electrochemical_utility_AFERefCfg_Type;
extern AD5940_ELECTROCHEMICAL_LPDACfg_Type utl_ad5940_electrochemical_utility_LPPACfg_Type;
extern AD5940_ELECTROCHEMICAL_LPTIACfg_Type utl_ad5940_electrochemical_utility_LPTIACfg_Type;
extern AD5940_ELECTROCHEMICAL_HSTIACfg_Type utl_ad5940_electrochemical_utility_HSTIACfg_Type;
extern AD5940_ELECTROCHEMICAL_DSPCfg_Type utl_ad5940_electrochemical_utility_DSPCfg_Type;

extern AD5940_ELECTROCHEMICAL_RUN_CONFIG ad5940_electrochemical_run_config;
extern AD5940_ELECTROCHEMICAL_LPDAC_TO_LPTIA_CONFIG ad5940_electrochemical_lpdac_to_lptia_config;
extern AD5940_ELECTROCHEMICAL_LPDAC_TO_HSTIA_CONFIG ad5940_electrochemical_lpdac_to_hstia_config;
extern AD5940_ELECTROCHEMICAL_HSDAC_MMR_TO_HSTIA_CONFIG ad5940_electrochemical_hsdac_mmr_to_hstia_config;

#ifdef __cplusplus
}
#endif
